# permissions for end users to view resourceattestations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourceattestation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourceattestation-viewer-role
rules:
- apiGroups:
  - argus.io
  resources:
  - componentattestations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argus.io
  resources:
  - componentattestations/status
  verbs:
  - get
