---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - argus.io
  resources:
  - assessments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - assessments/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - assessments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - attestationproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argus.io
  resources:
  - attestations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - attestations/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - attestations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - componentassessments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - componentassessments/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - componentassessments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - componentattestations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - componentattestations/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - componentattestations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - componentcontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - componentcontrols/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - componentcontrols/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argus.io
  resources:
  - controls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argus.io
  resources:
  - controls/finalizers
  verbs:
  - update
- apiGroups:
  - argus.io
  resources:
  - controls/status
  verbs:
  - get
  - patch
  - update
