apiVersion: argus.io/v1alpha1
kind: Attestation
metadata:
  labels:
    app.kubernetes.io/name: attestation
    app.kubernetes.io/instance: attestation-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: attestation1-req2
spec:
  implementationRef: "implementation1-req2"
  providerRef: 
    name: checkov
    namespace: default