apiVersion: argus.io/v1alpha1
kind: Control
metadata:
  name: sec-pol-ctrl-01
spec:
  definition: 
    version: 1.0.0
    code: SEC-POL-CTRL-01
    class: "Security"
    category: "Internal"
    description: "Container Registries must run in a private network"
  applicableComponentClasses:
  - ContainerRegistry
  requiredAssessmentClasses:
  - PreventativeControl